### ISSUE TITLE
`realpath` doesn't natively exist on macOS

### ISSUE THREAD

**Issue by georgettica** [openshift/boilerplate#186]
while running commands on my new machine I saw this error:
```
+++ realpath boilerplate/openshift/golang-osd-operator/ensure.sh
/Users/rogreen/Repo/route-monitor-operator/boilerplate/_lib/common.sh: line 146: realpath: command not found
```

and I saw that `realpath` can be used in `coreutils` and should be exported to the PATH variable before the defaults

also I found a macOS compatible function to get `realpath` https://stackoverflow.com/a/3572105

https://github.com/openshift/boilerplate/blob/6d709ee257e5329f5d0727620085941fa0855137/boilerplate/_lib/common.sh#L146

**Comment by 2uasimojo** [comment]
What commands were you running when you hit this?

**Comment by georgettica** [comment]
`make`

**Comment by 2uasimojo** [comment]
Is this still an issue, Ron? If installing realpath from coreutils does the trick, I'd say we can probably close this. If you have to do some other hackaround, please propose a PR to boilerplate that does something like
```sh
if ! type realpath >/dev/null 2>&1; then
  alias realpath=your_hackaround_here
fi
```
I don't have a Mac, or access to one, so I can't really help I'm afraid.

**Comment by georgettica** [comment]
It's ok, I will test it again :)

**Comment by georgettica** [comment]
let's close it with your suggestion :)
