### ISSUE TITLE
Building boilerplate image on s390x architecture

### ISSUE THREAD

**Issue by rposts** [openshift/boilerplate#191]
I noticed that [Dockerfile.appsre](https://github.com/openshift/boilerplate/blob/master/config/Dockerfile.appsre) is used to build boilerplate [image](https://quay.io/repository/app-sre/boilerplate) on x86.  I am trying to build this image on `s390x` but unable to find corresponding Dockerfile for [registry.ci.openshift.org/openshift/release:golang-1.16](https://github.com/openshift/boilerplate/blob/14ee3e27f250a7647436f18ac9bc7c651a05ce90/config/Dockerfile.appsre#L3).

Could someone please point me to instructions on building `registry.ci.openshift.org/openshift/release:golang-1.161` image?

Thanks.

**Comment by rposts** [comment]
Thanks @2uasimojo for your quick reply.

I am exploring ways to get [oadp-opeartor](https://github.com/openshift/oadp-operator) work on `s390x` arch.  Currently latest version of `oadp-operator` uses `boilerplate` [image](https://github.com/openshift/oadp-operator/blob/b62ca43bcaea0818a0dcd8bc2a8d41d1ff8417c6/Dockerfile#L3) as a base to build upon.  This will clearly not work on `s390x` arch which leads me to manually build `boilerplate` on this arch.

I hope this explains my use case.  Thanks.

**Comment by 2uasimojo** [comment]
What led you to pick the boilerplate backing image for that operator?

Anyway, if you need a s390x version of registry.ci.openshift.org/openshift/release:golang-1.16, you may want to start by tagging @dptp-helpdesk in #forum-testplatform on CoreOS slack. (I assume you're RH, given that your operator is under openshift.) They may or may not already have one; but at least they should be able to point you toward whatever sources those are built from.
