### ISSUE TITLE
Dependency Installation Broken For golangci-lint

### ISSUE THREAD

**Issue by dustman9000** [openshift/boilerplate#20]
The golangci-lint is broken. I'm using `gvm` and on a mac.

```
boilerplate/_lib/ensure.sh golangci-lint
tar: could not chdir to '/Users/dustinrow/.gvm/pkgsets/go1.13.6/global/bin'

make: *** [gocheck] Error 1
```

**Comment by 2uasimojo** [comment]
We should start figuring out how to run this stuff in a container rather than trying to anticipate every possible platform and environment.
