### ISSUE TITLE
Discussion on whether to include ginkgo.Recover() in test template

### ISSUE THREAD

**Issue by ritmun** [openshift/boilerplate#269]
https://github.com/openshift/boilerplate/blob/4d5d0556b6292ead4d4421b9b2e3cf08e5fbb7d1/boilerplate/openshift/golang-osd-operator-osde2e/e2e-harness-generate.sh#L50

When adding this line I thought each new harness would need to have its own recover() loop, that way we can enforce it from the get go. We can remove this from template if that's not needed. Thoughts?

**Comment by jbpratt** [comment]
So according to the Ginkgo documentation,

```
 However, if your spec launches a goroutine that calls Fail (or, equivalently, invokes a failing Gomega assertion), there's no way for Ginkgo to rescue the panic that Fail throws. This will cause the suite to panic and no subsequent specs will run. To get around this you must rescue the panic using defer GinkgoRecover().
```

Our use of it within osde2e is what causes the tests to hang when using the `util.GinkgoIt` wrapper. I think it should be used explicitly, when required (launching and asserting within a goroutine)

https://onsi.github.io/ginkgo/#mental-model-how-ginkgo-handles-failure

**Comment by ritmun** [comment]
I'll go ahead and remove it in https://github.com/openshift/boilerplate/pull/270
